### ISSUE TITLE
Review EUPMC code for Unpaywall use in getting PMC licenses

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/paradigm#46]
We currently have an interim way to update PMC licenses, but it's just for Gates. It's much higher impact to have Unpaywall to be able to do this.

## TODO

- [ ] Update Unpaywall on what we think - @josephmcarthur
- [ ] Give Unpaywall an OA.Works route - @markmacgillivray 
- [ ] Review code to double check all is as expected - @markmacgillivray 
- [ ] https://github.com/issues?q=is%3Aopen+is%3Aissue+assignee%3Amarkmacgillivray+archived%3Afalse+

**Comment by markmacgillivray** [comment]
Looks like they are happy to go straight to EPMC API themselves so I don't think we need to do this just now. EPMC improvements will be made along the way as we integrate more stuff into the new API for gates work, but I think we can close this one for now.
